application: stocks-wl
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /tasks/.*
  script: main.app

- url: /fonts
  static_dir: dist/fonts

- url: /assets
  static_dir: dist/assets

- url: /_ah/spi/.*
  script: services.APPLICATION

- url: .*
  static_files: dist/index.html
  login: required
  upload: dist/index.html
  secure: always

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: ssl
  version: latest
