application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: services.api_service.application

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0